version: '3.3'

services:
  users-service:
    container_name: app
    build:
      context: ./services/app
      dockerfile: Dockerfile-dev
    volumes:
      - './services/app:/usr/src/app'
    ports:
      - 5001:5000

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    depends_on:
      - app-service