version: '3.3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - './services/frontend:/usr/src/app'
      - './services/worker/data:/usr/src/app/data'
    ports:
      - 9292:9292
    depends_on:
      - mongodb
    links:
      - mongodb

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    depends_on:
      - frontend
    links:
      - frontend

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always

    #  redis:
    #container_name: redis
    #image: redis
    #environment:
    #  - ALLOW_EMPTY_PASSWORD=yes
    #ports:
    #  - '6379:6379'
    #restart: always
